//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebleShop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MebleDatabaseEntities2 : DbContext
    {
        public MebleDatabaseEntities2()
            : base("name=MebleDatabaseEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<IDAddress> IDAddress { get; set; }
        public virtual DbSet<Kitchen> Kitchen { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Styles> Styles { get; set; }
    }
}
