//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebleShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photos
    {
        public int IDkitchen { get; set; }
        public int idphoto { get; set; }
    }
}
